<a href="https://colab.research.google.com/github/bowsandrrows/googlpy/blob/main/Tensors01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Itroduction to Tensor
### Creating tensors

Pythorch Tensors are created using ´torch.Tensor()´

## Scalar

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Get tensor as python int
scalar.item()

7

In [4]:
scalar.ndim

0

## Vector


In [5]:
Vector = torch.tensor([7,7])
Vector

tensor([7, 7])

In [7]:
Vector.ndim

1

In [8]:
Vector.shape

torch.Size([2])

## MATRIX

In [11]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [12]:
MATRIX.ndim

2

In [19]:
MATRIX[0], MATRIX[1]

(tensor([1, 2]), tensor([3, 4]))

In [20]:
MATRIX.shape

torch.Size([2, 2])

## TENSOR

In [26]:
TENSOR = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [28]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [30]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [31]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 3, 3])

In [37]:
TENSOR = torch.tensor([
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
], dtype=torch.float32, device='cpu')
TENSOR

tensor([[1., 2., 3.],
        [3., 6., 9.],
        [2., 4., 5.]])

In [38]:
TENSOR = torch.tensor([
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [39]:
TENSOR.shape

torch.Size([3, 3])

Creates a 2D tensor of shape  — 3 rows, 3 columns.

In [40]:
TENSOR = torch.tensor([[
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [41]:
TENSOR.shape

torch.Size([1, 3, 3])

Creates a 3D tensor of shape  — 1 block (or batch), 3 rows, 3 columns.